name: Test Red Social
# Este flujo de trabajo se ejecuta cuando se abre una PR o se actualiza
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Instala Node.js (aquí usamos la versión 16, pero puedes cambiarla según tus necesidades)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    # Instala las dependencias del proyecto
    - name: Install dependencies
      run: npm install
    # Corre los tests de Jest
    - name: Run Jest tests
      run: npm run test
